apiVersion: v1
kind: Service
metadata:
  name: {{ include "feature-freeze.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "feature-freeze.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "feature-freeze.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
