apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "feature-freeze.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "feature-freeze.labels" . | nindent 4 }}
automountServiceAccountToken: false
